language: cpp

compiler:
  - gcc

python:
  - "3.4"

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - g++-4.9
      - libboost1.55-all-dev

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install:
  - sudo apt-get install libgc-dev
  # gtest & gmock
  - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - sudo tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - sudo cmake .
  - sudo make
  - sudo make install
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  cmake CMakeLists.txt -DPRECISE_GC=ON

script:
  - $CXX --version
  - make libprecisegc
  - make precisegc_test
  - ./test/precisegc_test
  - python tools/test_runner.py --cfg=tools/testcfg.json

notifications:
  email: false