language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - cmake
      - g++-4.9
    env: COMPILER=g++-4.9

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="g++-4.9"; fi

install:
  - sudo apt-get install libboost-dev

before_script:
  cmake CMakeLists.txt

script:
  - $CXX --version
  - make libprecisegc